// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evmdzkkanldwaggczync.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bWR6a2thbmxkd2FnZ2N6eW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODMzNzUsImV4cCI6MjA2Njg1OTM3NX0.mxTab5D4PUVK6YyoltkCWaxk3VXyobn7xh-9NcdC_K8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});